EntregaIweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MammaMia/', include('PizzeriaMammaMia.urls'))
]

PizzeriaMammaMia/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('pizza', views.PizzaListView.as_view(), name='index_pizzas'),
    path('pizza/<int:pk>',views.PizzaDetailView.as_view(), name='show_pizza'),
    path('ingrediente', views.IngredienteListView.as_view(),name='index_ingredientes'),
    path('ingrediente/<int:ingrediente_id>', views.show_ingrediente,name='show_ingrediente'),
    path('masa', views.MasaListView.as_view(),name='index_masas'),
    path('masa/<int:masa_id>', views.show_masa,name='show_masa'),

]

PizzeriaMammaMia/models.py
from django.db import models

# Create your models here.

class Ingrediente(models.Model):
    nombre= models.CharField(max_length=50)
    def __str__(self):
        return f"id={self.id}, nombre={self.nombre}"
    descripcion=models.CharField(max_length=1024) # o más incluso



class Masa(models.Model):
    nombre= models.CharField(max_length=50)
    precio= models.IntegerField(default=1)
    def __str__(self):
        return f"id={self.id}, nombre={self.nombre}"
    descripcion=models.CharField(max_length=1024) # o más incluso


class Pizza(models.Model):
    nombre= models.CharField(max_length=50)
    def __str__(self):
        return f"id={self.id}, nombre={self.nombre}"
    descripcion=models.CharField(max_length=1024) # o más incluso
    #Relacion many-to-many con los ingredientes
    ingredientes = models.ManyToManyField(Ingrediente, related_name='pizzas')
    #Relacion one-to-many con las masas
    masa = models.ForeignKey(Masa,related_name='pizzas', on_delete=models.CASCADE)
    precio = models.IntegerField(default=0)

PizzeriaMammaMia/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, get_list_or_404
from django.views.generic import DetailView, ListView
from .models import *

# Create your views here.

def landing(request):
    pizzas = []
    
    tiposdemasa = get_list_or_404(Masa.objects.order_by('id'))
    for i in tiposdemasa:
        pizzs = get_list_or_404(Pizza.objects.order_by('precio'),masa=i)
        pizzas.append(pizzs[0])

    context = {'pizzas' : pizzas}
    return render(request,'landing.html',context)
    
class PizzaDetailView(DetailView):
    model = Pizza
    template_name = 'pizza.html'
    def get_context_data(self, **kwargs):
        context = super(PizzaDetailView,self).get_context_data(**kwargs)
        return context

#def show_pizza(request,pizza_id):
#    pizza = get_object_or_404(Pizza, pk=pizza_id)
#    masa = pizza.masa
#    ingredientes = pizza.ingredientes.all()
#    context = {'pizza' : pizza , 'masa': masa, 'ingredientes' : ingredientes}
#    return render(request,'pizza.html',context)

class PizzaListView(ListView):
    model = Pizza
    template_name = 'pizzas.html'
    queryset = Pizza.objects.order_by('id')

#def index_pizzas(request):
 #   pizzas = get_list_or_404(Pizza.objects.order_by('nombre'))
  #  context = {'lista_pizzas' : pizzas}
   # return render(request, 'pizzas.html', context)

#class MasaDetailView(DetailView):
#    model = Masa
#    template_name = 'masa.html'
#    
#    def get_context_data(self, **kwargs):
#        context = super(MasaDetailView,self).get_context_data(**kwargs)
#        #TODO pizzas = get_list_or_404(Pizza,masa)
#        return context

def show_masa(request,masa_id):
    masa = get_object_or_404(Masa,pk=masa_id)
    pizzas = get_list_or_404(Pizza,masa=masa_id)
    context = {'masa' : masa, 'pizzas' : pizzas}
    return render(request, 'masa.html', context)

class MasaListView(ListView):
    model : Masa
    template_name = "masas.html"
    queryset = Masa.objects.order_by('id')

#def index_masas(request):
#    masas = get_list_or_404(Masa.objects.order_by('nombre'))
#    context = {'masas' : masas}
#    return render(request, 'masas.html', context)



def show_ingrediente(request,ingrediente_id):
    ingrediente = get_object_or_404(Ingrediente,pk=ingrediente_id)
    pizzas = get_list_or_404(Pizza,ingredientes=ingrediente_id)
    context = {'ingrediente' : ingrediente, 'pizzas' : pizzas}
    return render(request, 'ingrediente.html', context)
        
class IngredienteListView(ListView):
    model : Ingrediente
    template_name = "ingredientes.html"
    queryset = Ingrediente.objects.order_by('id')     

#def index_ingredientes(request):
#    ingredientes = get_list_or_404(Ingrediente.objects.order_by('nombre'))
#    context = {'ingredientes' : ingredientes}
#       return render(request, 'ingredientes.html', context)

PizzeriaMammaMia/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="es">
    <head>
        <link rel="stylesheet" href={% static 'css/styles.css' %}>
        <title>{% block titulo  %}{% endblock titulo  %}</title>
    </head>
    <body>
        <header>
            <nav class="topbar">
                <ul>
                    <li><a class="active" href={% url 'landing' %}>Pizzeria Mamma Mia</a></li>
                    <li><a href={% url 'index_pizzas' %}>Nuestras Pizzas</a></li>
                    <li><a href={% url 'index_masas' %}>Masas</a></li>
                    <li><a href={% url 'index_ingredientes' %}>Ingredientes</a></li>
                </ul>
            </nav>
        </header>
        <div id="content">
                {% block contenido %}{% endblock contenido %}
        </div>
        <script src={% static 'JS/script.js' %}></script>
    </body>
</html>

PizzeriaMammaMia/templates/ingrediente.html
{% extends 'base.html' %}
{% block titulo %} {{ingrediente.nombre}} {% endblock titulo %}

{% block contenido %}
<h2> {{ingrediente.nombre}} </h2>
{% if ingrediente %}
    <!-- una foto del ingrediente estaría bien-->
    <p> {{ingrediente.descripcion}} </p>
    <!-- TODO poner todas las pizzas que tienen este ingrediente-->
    <h3>Pizzas con estos ingredientes </h3>
    <ul>
    {% for piz in pizzas %}
        <li><a href="{% url 'show_pizza' piz.id %}"> {{piz.nombre}}</a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p> No existe el ingrediente que estas buscando. Vuelve al inicio? </p> 
    <!--TODO añadir un enlace al landing o mirar si se puede hacer un 404 personalizado-->
    <!-- ahora que lo miro este ifelse es inutil si estoy usando get_or_404 -->
{% endif %}    



{% endblock contenido %}

PizzeriaMammaMia/templates/ingredientes.html
{% extends 'base.html' %}
{% block titulo %} Ingredientes {% endblock titulo %}

{% block contenido %}
<h2> Lista de ingredientes </h2>
    <ul>
        {% for i in ingrediente_list %}
        <li>
            <a href="{% url 'show_ingrediente' i.id%}">{{i.nombre}} </a>
        </li>
        {% endfor %}
    </ul>    

{% endblock contenido %}

PizzeriaMammaMia/templates/landing.html
{% extends 'base.html' %}
{% block titulo %} {{nombre}} {% endblock titulo %}
{% block contenido %}
<h2> ¡Bienvenuto a la Pizzería Mamma Mia!</h2>
<p>Prueba algunas de nuestras pizzas:</p>
<ul>
    {% for piz in pizzas %}
        <li>
            <a href="{% url 'show_pizza' piz.id%}">{{piz.nombre}}</a>
        </li>   
    {% endfor %}
</ul>
{% endblock contenido %}

PizzeriaMammaMia/templates/masa.html
{% extends 'base.html' %}
{% block titulo %} {{masa.nombre}} {% endblock titulo %}
{% block contenido %} 
<h2>{{masa.nombre}}</h2>

    <!-- una foto de la masa estaría bien-->
    <p> {{masa.descripcion}}
    <h3>Pizzas Con Esta Masa </h3>
    <ul>
        {% for piz in pizzas %}
            <li><a href="{% url 'show_pizza' piz.id %}"> {{piz.nombre}}</a> </li>
        {% endfor %}
    </ul>


{% endblock contenido %}

PizzeriaMammaMia/templates/masas.html
{% extends 'base.html' %}
{% block titulo %} Masas {% endblock titulo %}

{% block contenido %}
<h2> Lista de masas </h2>

    <ul>
        {% for i in masa_list %}
        <li>
            <a href = {% url 'show_masa' i.id %}>{{i.nombre}} </a>
        </li>
        {% endfor %}
    </ul>    


{% endblock contenido %} 

PizzeriaMammaMia/templates/pizza.html
{% extends 'base.html' %}
{% block titulo %} {{ingrediente.nombre}} {% endblock titulo %}
{% block contenido %} 
<h2>{{pizza.nombre}}</h2>
    <!-- una foto de la pizza estaría bien-->
    <p> {{pizza.descripcion}}</p>
    <h3> Masa: </h3>
    <p><a href="{% url 'show_masa' pizza.masa.id %}">{{pizza.masa.nombre}}</a></p>
    <h3> Ingredientes: </h3>
    <ul>
    {% for i in ingredientes %}
        <li><a href="{% url 'show_ingrediente' i.id%}"> {{i.nombre}} </a></li>
    {% endfor %}
    </ul>
<h3>Precio </h3>
 <p>{{pizza.precio}}€</p> 
 <hr>
 <h3> Pedido online </h3>
<textarea id="pedidobox" placeholder="Introduce la dirección a la que quieres recibir la pizza"></textarea>
<br>    

<button onclick="comprarPizza()">Pedir</button>


{% endblock contenido %}

PizzeriaMammaMia/templates/pizzas.html
{% extends 'base.html' %}
{% block titulo %} Pizzas {% endblock titulo %}
{% block contenido %}
<h2> Lista de pizzas </h2>

    <ul>
       
         {% for i in pizza_list %}
        <li>
            <a href="{% url 'show_pizza' i.id %}">{{i.nombre}} </a> 
        </li>
        {% endfor %}

    </ul>    


{% endblock contenido %} 